[project]
name = "koog-docs"
# keep it synced with Koog version
version = "0.4.1"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-material==9.6.19",
    "mkdocs-redirects==1.2.2",
    "mkdocs-llmstxt==0.3.1",
]
